# Generated by Django 3.1.6 on 2021-02-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210211_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='graph_description',
            new_name='graph_image',
        ),
    ]
