# Generated by Django 3.1.6 on 2021-02-11 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210211_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 17, 38, 36, 684353), verbose_name='date published'),
        ),
    ]
