# Generated by Django 3.1.6 on 2021-02-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_title', models.CharField(max_length=200)),
                ('graph_description', models.TextField()),
                ('graph_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
