# Generated by Django 3.1.6 on 2021-02-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_description',
            field=models.ImageField(upload_to=''),
        ),
    ]
