# Generated by Django 3.1.6 on 2021-02-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_coord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coord',
            name='x',
        ),
        migrations.RemoveField(
            model_name='coord',
            name='y',
        ),
    ]
