# Generated by Django 3.1.6 on 2021-02-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210224_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coord',
        ),
    ]
